### ISSUE TITLE
[MAJOR]

### ISSUE THREAD

**Issue by stenolog** [stenolog/ton#3]
The current TON Source Code Tree is undocumented

What is missing:

* A) architectural/structural overview
  * barrier: there is no structure, it's a flat source tree
* B) summarizing doc for each root folder
  * filed within: https://github.com/ton-society/grants-and-bounties/issues/266
* C) documentation header per source-file (where applicable/needed)
  * barrier: license headers

### Context

This is partially in context of this issue:

- https://github.com/ton-society/grants-and-bounties/issues/266

### Tasks Done
- [ ] https://github.com/ton-blockchain/ton/pull/924

### Further Tasks

- [ ] Introduce "Doxygen" (or similar) Code Documentation
- [ ] Identify the major subsystems (exe, lib) that need to be documented first:
  - #1
  - [ ] Document `blockchain-explorer` (source & usage)
  - [ ] Document `dht-server` (source & usage)
  - [ ] Document `http` (source & usage)
  - [ ] Document `lite-client` (sources)
  - [ ] Document `rldp-http-proxy` (source)
  - [ ] Document `storage` (source)
  - [ ] Document `tdactor` (source)
  - [ ] Document `validator` sources
  - #2 
  - [ ] Document each folder listed under `libraries` (sources & usage)
  - during work, move/list further relevant **executables** under `executables`

### Spawned Issues

Issues that came up during work on this.

* TON Primer outdated: https://ton.org/primer.pdf
